### PR TITLE
Meta: Review Draft infrastructure

### PR DESCRIPTION
**Pull request by foolip**
See https://github.com/whatwg/whatwg.org/issues/197 for details.

### CODE REVIEW

**Comment by annevk** [comment]
Thanks for helping out. You'll want to update the README too.

**Comment by foolip** [comment]
I saw the README changes in https://github.com/whatwg/url/pull/387 but they seem unrelated, am I missing a connection?

**Comment by annevk** [comment]
I guess they are a bit, but it seems worthwhile grouping Meta changes together. It's basically about making the instructions a little better for new folks. Nobody should really bother with setting up Bikeshed or even building locally necessarily these days.

**Comment by annevk** [comment]
Yeah, that's not a bad idea and I was thinking that too, but didn't go for it for unclear reasons. @domenic?

**Comment by domenic** [comment]
Seems reasonable, as long as local is still an option.

**Comment by annevk** [comment]
I pushed a commit that aligns this with other outstanding PRs.

**Comment by annevk** [comment]
Mentioning https://github.com/whatwg/meta/issues/92 for the backlink.

**Pull request merged**
