### PR TITLE
Let the UA end fullscreen unilaterally.

### PR DESCRIPTION
**Pull request by avidrissman**
***
[Preview](https://s3.amazonaws.com/pr-preview/avidrissman/fullscreen/dialog.html) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/fullscreen/4ad4ab0...avidrissman:3ea61d7.html)

### CODE REVIEW

**Comment by annevk** [comment]
Before merging this the concerns in https://github.com/whatwg/fullscreen/issues/93#issuecomment-312397283 need to be addressed somehow. Although UX is always up to the UA, if every UA is forced to have the same UX due to compat we should be a little careful.

**Comment by avidrissman** [comment]
@foolip, if you're happy with the PR, feel free to merge it, as I cannot. If you want any changes before you merge it, please let me know.

**Comment by foolip** [comment]
@avidrissman, I thought I would give @upsuper a chance to reply on https://github.com/whatwg/fullscreen/issues/93#issuecomment-313371863.

I'm about to go on vacation for the rest of July. @annevk, can you merge this if https://github.com/whatwg/fullscreen/issues/93 settles in favor of this approach?

**Comment by annevk** [comment]
I can. The only nit I have (which I cannot fix myself since edits from maintainers appears to be disabled) is that an additional newline should be added before the `<h2>`.

**Comment by avidrissman** [comment]
@annevk Please take a look.

**Comment by annevk** [comment]
Thanks, I still think we should wait on @upsuper though as @foolip also indicated.

**Comment by avidrissman** [comment]
ping?

**Comment by annevk** [comment]
Went ahead given the reluctant okay in the corresponding issue. Thanks all!

**Pull request merged**
