### PR TITLE
Review Draft Publication: January 2020

### PR DESCRIPTION
**Pull request by annevk**
A Review Draft for this Workstream will be published shortly, by merging this pull request.

Under the [WHATWG IPR Policy](https://whatwg.org/ipr-policy), Participants may, within 45 days after publication of a Review Draft, exclude certain Essential Patent Claims from the Review Draft Licensing Obligations. See the [IPR Policy](https://whatwg.org/ipr-policy) for details.

### CODE REVIEW

**Comment by annevk** [comment]
It seems this is failing due to #153 @foolip?

**Comment by foolip** [comment]
https://github.com/whatwg/fullscreen/pull/153 hasn't been merged yet, but it's related. It's because https://github.com/whatwg/html/pull/3851 removed the concept. Looks like https://html.spec.whatwg.org/#transient-activation is the new deal, I'll send a PR.

**Comment by foolip** [comment]
I've sent https://github.com/whatwg/fullscreen/pull/163 which passes CI.

**Comment by annevk** [comment]
This moved to #164.

**Pull request closed without merging**
