### PR TITLE
Meta: align with whatwg/meta resources

### PR DESCRIPTION
**Pull request by annevk**
Helps with https://github.com/whatwg/meta/issues/65.

### CODE REVIEW

**Comment by annevk** [comment]
Title should be: "Meta: reference whatwg/meta resources".

**Comment by snuggs** [comment]
@annevk can you change title? I believe you're the one that created this unless i'm missing something.

**Comment by annevk** [comment]
I don't care much about the PR title, I meant the commit title which I'll adjust when hitting squash & commit.

**Comment by snuggs** [comment]
Copy that!

**Pull request merged**
